import { type RouteConfig, index, route } from "@react-router/dev/routes";

export default [
  index("routes/home.tsx"),
  route("login", "routes/login.tsx"),
  route("students", "routes/students.tsx"),
  route("teachers", "routes/teachers.tsx"),
  route("courses", "routes/courses.tsx"),
  route("majors", "routes/majors.tsx"),
  route("categories/buildings", "routes/categories/buildings.tsx"),
  route("categories/floors", "routes/categories/floors.tsx"),
  route("categories/rooms", "routes/categories/rooms.tsx"),
  route("categories/provinces", "routes/categories/provinces.tsx"),
  route("categories/districts", "routes/categories/districts.tsx"),
  route("categories/wards", "routes/categories/wards.tsx"),
  route("class-groups", "routes/class-groups.tsx"),
  route("schedule", "routes/schedule.tsx"),
  route("schedule/timetable", "routes/schedules/timetable.tsx"),
  route("schedule/class", "routes/schedules/class.tsx"),
  route("schedule/exam", "routes/schedules/exam.tsx"),
  route("schedule/teaching", "routes/schedules/teaching.tsx"),
  route("grades", "routes/grades.tsx"),
  route("transcripts", "routes/transcripts.tsx"),
  route("users", "routes/users.tsx"),
  route("notifications", "routes/notifications.tsx"),
] satisfies RouteConfig;
